# Generated by Django 5.1.1 on 2024-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='isinstance',
            field=models.BooleanField(default=False),
        ),
    ]
