# Generated by Django 5.1.1 on 2024-09-11 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staffattendance_isinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='main.staff'),
        ),
    ]
